#include "inputconfig.hpp"

#include <qdir.h>
#include <qfile.h>
#include <qfileinfo.h>
#include <qlocalsocket.h>
#include <qloggingcategory.h>
#include <qsavefile.h>
#include <qstandardpaths.h>
#include <qtextstream.h>

namespace caelestia::config {

InputConfig::InputConfig(QObject* parent)
    : ConfigObject(parent) {
    connect(this, &ConfigObject::propertiesChanged, this, [this] {
        applyInputSettings();
    });
}

void InputConfig::applyInputSettings() {
    saveGeneratedConfig();
    dispatchCompositorIpc();
}

void InputConfig::setDeviceSetting(const QString& deviceName, const QString& key, const QVariant& value) {
    if (deviceName.isEmpty() || key.isEmpty())
        return;
    QVariantMap devMap = devices();
    QVariantMap opts = devMap.value(deviceName).toMap();
    opts.insert(key, value);
    devMap.insert(deviceName, opts);
    set_devices(devMap);
}

QVariant InputConfig::deviceSetting(const QString& deviceName, const QString& key, const QVariant& defaultValue) const {
    const QVariantMap devMap = devices();
    if (!devMap.contains(deviceName))
        return defaultValue;
    const QVariantMap opts = devMap.value(deviceName).toMap();
    return opts.value(key, defaultValue);
}

void InputConfig::removeDeviceSetting(const QString& deviceName, const QString& key) {
    if (deviceName.isEmpty())
        return;
    QVariantMap devMap = devices();
    if (!devMap.contains(deviceName))
        return;

    if (key.isEmpty()) {
        devMap.remove(deviceName);
    } else {
        QVariantMap opts = devMap.value(deviceName).toMap();
        opts.remove(key);
        if (opts.isEmpty()) {
            devMap.remove(deviceName);
        } else {
            devMap.insert(deviceName, opts);
        }
    }
    set_devices(devMap);
}

QString InputConfig::generateLuaConfig() const {
    QString lua;
    QTextStream out(&lua);
    out << "-- Generated by Caelestia Input Config Manager\n";
    out << "-- Do not edit directly; values are persisted in shell.json\n\n";
    out << "return {\n";
    out << "  input = {\n";
    out << QString("    sensitivity = %1,\n").arg(pointerSpeed());
    out << "    touchpad = {\n";
    out << QString("      tap_to_click = %1,\n").arg(touchpadTapToClick() ? QStringLiteral("true") : QStringLiteral("false"));
    out << QString("      natural_scroll = %1,\n").arg(touchpadNaturalScroll() ? QStringLiteral("true") : QStringLiteral("false"));
    out << "    },\n";
    out << QString("    repeat_rate = %1,\n").arg(keyboardRepeatRate());
    out << QString("    repeat_delay = %1,\n").arg(keyboardRepeatDelay());
    out << "  },\n";

    const QVariantMap devMap = devices();
    if (!devMap.isEmpty()) {
        out << "  device = {\n";
        for (auto it = devMap.constBegin(); it != devMap.constEnd(); ++it) {
            out << QString("    [\"%1\"] = {\n").arg(it.key());
            if (it.value().canConvert<QVariantMap>()) {
                const QVariantMap devOpts = it.value().toMap();
                for (auto optIt = devOpts.constBegin(); optIt != devOpts.constEnd(); ++optIt) {
                    QString key = optIt.key();
                    if (key == QStringLiteral("pointerSpeed") || key == QStringLiteral("sensitivity")) {
                        out << QString("      sensitivity = %1,\n").arg(optIt.value().toDouble());
                    } else if (key == QStringLiteral("touchpadTapToClick") || key == QStringLiteral("tap_to_click")) {
                        out << QString("      tap_to_click = %1,\n").arg(optIt.value().toBool() ? QStringLiteral("true") : QStringLiteral("false"));
                    } else if (key == QStringLiteral("touchpadNaturalScroll") || key == QStringLiteral("natural_scroll")) {
                        out << QString("      natural_scroll = %1,\n").arg(optIt.value().toBool() ? QStringLiteral("true") : QStringLiteral("false"));
                    } else if (key == QStringLiteral("keyboardRepeatRate") || key == QStringLiteral("repeat_rate")) {
                        out << QString("      repeat_rate = %1,\n").arg(optIt.value().toInt());
                    } else if (key == QStringLiteral("keyboardRepeatDelay") || key == QStringLiteral("repeat_delay")) {
                        out << QString("      repeat_delay = %1,\n").arg(optIt.value().toInt());
                    } else {
                        out << QString("      [\"%1\"] = \"%2\",\n").arg(key, optIt.value().toString());
                    }
                }
            }
            out << "    },\n";
        }
        out << "  },\n";
    }

    out << "}\n";
    return lua;
}

QString InputConfig::generateConfConfig() const {
    QString conf;
    QTextStream out(&conf);
    out << "# Generated by Caelestia Input Config Manager\n";
    out << "# Do not edit directly; values are persisted in shell.json\n\n";
    out << "input {\n";
    out << QString("    sensitivity = %1\n").arg(pointerSpeed());
    out << "    touchpad {\n";
    out << QString("        tap-to-click = %1\n").arg(touchpadTapToClick() ? QStringLiteral("true") : QStringLiteral("false"));
    out << QString("        natural_scroll = %1\n").arg(touchpadNaturalScroll() ? QStringLiteral("true") : QStringLiteral("false"));
    out << "    }\n";
    out << QString("    repeat_rate = %1\n").arg(keyboardRepeatRate());
    out << QString("    repeat_delay = %1\n").arg(keyboardRepeatDelay());
    out << "}\n\n";

    const QVariantMap devMap = devices();
    for (auto it = devMap.constBegin(); it != devMap.constEnd(); ++it) {
        out << "device {\n";
        out << QString("    name = %1\n").arg(it.key());
        if (it.value().canConvert<QVariantMap>()) {
            const QVariantMap devOpts = it.value().toMap();
            for (auto optIt = devOpts.constBegin(); optIt != devOpts.constEnd(); ++optIt) {
                QString key = optIt.key();
                if (key == QStringLiteral("pointerSpeed") || key == QStringLiteral("sensitivity")) {
                    out << QString("    sensitivity = %1\n").arg(optIt.value().toDouble());
                } else if (key == QStringLiteral("touchpadTapToClick") || key == QStringLiteral("tap_to_click")) {
                    out << QString("    tap-to-click = %1\n").arg(optIt.value().toBool() ? QStringLiteral("true") : QStringLiteral("false"));
                } else if (key == QStringLiteral("touchpadNaturalScroll") || key == QStringLiteral("natural_scroll")) {
                    out << QString("    natural_scroll = %1\n").arg(optIt.value().toBool() ? QStringLiteral("true") : QStringLiteral("false"));
                } else if (key == QStringLiteral("keyboardRepeatRate") || key == QStringLiteral("repeat_rate")) {
                    out << QString("    repeat_rate = %1\n").arg(optIt.value().toInt());
                } else if (key == QStringLiteral("keyboardRepeatDelay") || key == QStringLiteral("repeat_delay")) {
                    out << QString("    repeat_delay = %1\n").arg(optIt.value().toInt());
                } else {
                    out << QString("    %1 = %2\n").arg(key, optIt.value().toString());
                }
            }
        }
        out << "}\n\n";
    }

    return conf;
}

QString InputConfig::generateConfig(bool forceLua) const {
    if (usingLua() || forceLua) {
        return generateLuaConfig();
    }
    return generateConfConfig();
}

bool InputConfig::saveGeneratedConfig(const QString& customFilePath, bool forceLua) {
    QString targetPath = customFilePath;
    const bool isLua = usingLua() || forceLua;
    if (targetPath.isEmpty()) {
        QString configDir = QStandardPaths::writableLocation(QStandardPaths::GenericConfigLocation) + QStringLiteral("/caelestia/generated/");
        QDir().mkpath(configDir);
        targetPath = configDir + (isLua ? QStringLiteral("input.lua") : QStringLiteral("input.conf"));
    } else {
        QFileInfo info(targetPath);
        QDir().mkpath(info.absolutePath());
    }

    QString content = generateConfig(isLua);

    QSaveFile saveFile(targetPath);
    if (!saveFile.open(QIODevice::WriteOnly | QIODevice::Text)) {
        qCWarning(lcConfig) << "InputConfig::saveGeneratedConfig: Unable to open QSaveFile for" << targetPath;
        return false;
    }

    QTextStream out(&saveFile);
    out << content;
    out.flush();

    if (!saveFile.commit()) {
        qCWarning(lcConfig) << "InputConfig::saveGeneratedConfig: Atomic commit failed for" << targetPath;
        return false;
    }

    return true;
}

bool InputConfig::dispatchCompositorIpc() {
    const auto his = qEnvironmentVariable("HYPRLAND_INSTANCE_SIGNATURE");
    if (his.isEmpty()) {
        return false;
    }

    auto hyprDir = QString("%1/hypr/%2").arg(qEnvironmentVariable("XDG_RUNTIME_DIR"), his);
    if (!QDir(hyprDir).exists()) {
        hyprDir = QStringLiteral("/tmp/hypr/") + his;
        if (!QDir(hyprDir).exists()) {
            return false;
        }
    }

    QString socketPath = hyprDir + QStringLiteral("/.socket.sock");
    QLocalSocket socket;
    socket.connectToServer(socketPath);
    if (!socket.waitForConnected(150)) {
        qCWarning(lcConfig) << "InputConfig::dispatchCompositorIpc: Socket connection failed for" << socketPath;
        return false;
    }

    QStringList cmds;

    if (usingLua()) {
        QString luaInput = QStringLiteral("eval hl.config({ input = { sensitivity = %1, touchpad = { tap_to_click = %2, natural_scroll = %3 }, repeat_rate = %4, repeat_delay = %5 } })")
            .arg(pointerSpeed())
            .arg(touchpadTapToClick() ? QStringLiteral("true") : QStringLiteral("false"))
            .arg(touchpadNaturalScroll() ? QStringLiteral("true") : QStringLiteral("false"))
            .arg(keyboardRepeatRate())
            .arg(keyboardRepeatDelay());
        cmds.append(luaInput);

        const QVariantMap devMap = devices();
        for (auto it = devMap.constBegin(); it != devMap.constEnd(); ++it) {
            if (it.value().canConvert<QVariantMap>()) {
                const QVariantMap opts = it.value().toMap();
                QStringList devOptsLua;
                for (auto oIt = opts.constBegin(); oIt != opts.constEnd(); ++oIt) {
                    QString k = oIt.key();
                    if (k == QStringLiteral("pointerSpeed") || k == QStringLiteral("sensitivity")) {
                        devOptsLua.append(QStringLiteral("sensitivity = %1").arg(oIt.value().toDouble()));
                    } else if (k == QStringLiteral("touchpadTapToClick") || k == QStringLiteral("tap_to_click")) {
                        devOptsLua.append(QStringLiteral("tap_to_click = %1").arg(oIt.value().toBool() ? QStringLiteral("true") : QStringLiteral("false")));
                    } else if (k == QStringLiteral("touchpadNaturalScroll") || k == QStringLiteral("natural_scroll")) {
                        devOptsLua.append(QStringLiteral("natural_scroll = %1").arg(oIt.value().toBool() ? QStringLiteral("true") : QStringLiteral("false")));
                    } else if (k == QStringLiteral("keyboardRepeatRate") || k == QStringLiteral("repeat_rate")) {
                        devOptsLua.append(QStringLiteral("repeat_rate = %1").arg(oIt.value().toInt()));
                    } else if (k == QStringLiteral("keyboardRepeatDelay") || k == QStringLiteral("repeat_delay")) {
                        devOptsLua.append(QStringLiteral("repeat_delay = %1").arg(oIt.value().toInt()));
                    }
                }
                if (!devOptsLua.isEmpty()) {
                    cmds.append(QStringLiteral("eval hl.config({ device = { [\"%1\"] = { %2 } } })")
                        .arg(it.key(), devOptsLua.join(QStringLiteral(", "))));
                }
            }
        }
    } else {
        cmds.append(QStringLiteral("keyword input:sensitivity %1").arg(pointerSpeed()));
        cmds.append(QStringLiteral("keyword input:touchpad:tap-to-click %1").arg(touchpadTapToClick() ? 1 : 0));
        cmds.append(QStringLiteral("keyword input:touchpad:natural_scroll %1").arg(touchpadNaturalScroll() ? 1 : 0));
        cmds.append(QStringLiteral("keyword input:repeat_rate %1").arg(keyboardRepeatRate()));
        cmds.append(QStringLiteral("keyword input:repeat_delay %1").arg(keyboardRepeatDelay()));

        const QVariantMap devMap = devices();
        for (auto it = devMap.constBegin(); it != devMap.constEnd(); ++it) {
            if (it.value().canConvert<QVariantMap>()) {
                const QVariantMap opts = it.value().toMap();
                for (auto oIt = opts.constBegin(); oIt != opts.constEnd(); ++oIt) {
                    QString k = oIt.key();
                    if (k == QStringLiteral("pointerSpeed") || k == QStringLiteral("sensitivity")) {
                        cmds.append(QStringLiteral("keyword device[%1]:sensitivity %2").arg(it.key()).arg(oIt.value().toDouble()));
                    } else if (k == QStringLiteral("touchpadTapToClick") || k == QStringLiteral("tap_to_click")) {
                        cmds.append(QStringLiteral("keyword device[%1]:tap-to-click %2").arg(it.key()).arg(oIt.value().toBool() ? 1 : 0));
                    } else if (k == QStringLiteral("touchpadNaturalScroll") || k == QStringLiteral("natural_scroll")) {
                        cmds.append(QStringLiteral("keyword device[%1]:natural_scroll %2").arg(it.key()).arg(oIt.value().toBool() ? 1 : 0));
                    } else if (k == QStringLiteral("keyboardRepeatRate") || k == QStringLiteral("repeat_rate")) {
                        cmds.append(QStringLiteral("keyword device[%1]:repeat_rate %2").arg(it.key()).arg(oIt.value().toInt()));
                    } else if (k == QStringLiteral("keyboardRepeatDelay") || k == QStringLiteral("repeat_delay")) {
                        cmds.append(QStringLiteral("keyword device[%1]:repeat_delay %2").arg(it.key()).arg(oIt.value().toInt()));
                    }
                }
            }
        }
    }

    QString payload = QStringLiteral("[[BATCH]]") + cmds.join(QStringLiteral(";"));
    socket.write(payload.toUtf8());
    socket.flush();

    if (!socket.waitForBytesWritten(150)) {
        qCWarning(lcConfig) << "InputConfig::dispatchCompositorIpc: Socket write failed";
        socket.close();
        return false;
    }

    if (socket.waitForReadyRead(150)) {
        QByteArray response = socket.readAll();
        qCDebug(lcConfig) << "InputConfig::dispatchCompositorIpc: Response received:" << response;
    }

    socket.close();
    return true;
}

} // namespace caelestia::config
