#include "inputconfig.hpp"

#include <qdir.h>
#include <qfile.h>
#include <qfileinfo.h>
#include <qlocalsocket.h>
#include <qloggingcategory.h>
#include <qsavefile.h>
#include <qstandardpaths.h>
#include <qtextstream.h>

namespace caelestia::config {

InputConfig::InputConfig(QObject* parent)
    : ConfigObject(parent) {
    connect(this, &ConfigObject::propertiesChanged, this, [this] {
        applyInputSettings();
    });
}

void InputConfig::applyInputSettings() {
    saveGeneratedConfig();
    dispatchCompositorIpc();
}

void InputConfig::setDeviceSetting(const QString& deviceName, const QString& key, const QVariant& value) {
    if (deviceName.isEmpty() || key.isEmpty())
        return;
    QVariantMap devMap = devices();
    QVariantMap opts = devMap.value(deviceName).toMap();
    opts.insert(key, value);
    devMap.insert(deviceName, opts);
    set_devices(devMap);
}

QVariant InputConfig::deviceSetting(const QString& deviceName, const QString& key, const QVariant& defaultValue) const {
    const QVariantMap devMap = devices();
    if (!devMap.contains(deviceName))
        return defaultValue;
    const QVariantMap opts = devMap.value(deviceName).toMap();
    return opts.value(key, defaultValue);
}

void InputConfig::removeDeviceSetting(const QString& deviceName, const QString& key) {
    if (deviceName.isEmpty())
        return;
    QVariantMap devMap = devices();
    if (!devMap.contains(deviceName))
        return;

    if (key.isEmpty()) {
        devMap.remove(deviceName);
    } else {
        QVariantMap opts = devMap.value(deviceName).toMap();
        opts.remove(key);
        if (opts.isEmpty()) {
            devMap.remove(deviceName);
        } else {
            devMap.insert(deviceName, opts);
        }
    }
    set_devices(devMap);
}

QString InputConfig::generateLuaConfig() const {
    QString lua;
    QTextStream out(&lua);
    out << "-- Generated by Caelestia Input Config Manager\n";
    out << "-- Do not edit directly; values are persisted in shell.json\n\n";
    out << "return {\n";
    out << "  input = {\n";
    out << QString("    sensitivity = %1,\n").arg(pointerSpeed());
    out << "    touchpad = {\n";
    out << QString("      tap_to_click = %1,\n").arg(touchpadTapToClick() ? QStringLiteral("true") : QStringLiteral("false"));
    out << QString("      natural_scroll = %1,\n").arg(touchpadNaturalScroll() ? QStringLiteral("true") : QStringLiteral("false"));
    out << "    },\n";
    out << QString("    repeat_rate = %1,\n").arg(keyboardRepeatRate());
    out << QString("    repeat_delay = %1,\n").arg(keyboardRepeatDelay());
    out << "  },\n";

    const QVariantMap devMap = devices();
    if (!devMap.isEmpty()) {
        out << "  device = {\n";
        for (auto it = devMap.constBegin(); it != devMap.constEnd(); ++it) {
            out << QString("    [\"%1\"] = {\n").arg(it.key());
            if (it.value().canConvert<QVariantMap>()) {
                const QVariantMap devOpts = it.value().toMap();
                for (auto optIt = devOpts.constBegin(); optIt != devOpts.constEnd(); ++optIt) {
                    QString key = optIt.key();
                    if (key == QStringLiteral("pointerSpeed") || key == QStringLiteral("sensitivity")) {
                        out << QString("      sensitivity = %1,\n").arg(optIt.value().toDouble());
                    } else if (key == QStringLiteral("touchpadTapToClick") || key == QStringLiteral("tap_to_click")) {
                        out << QString("      tap_to_click = %1,\n").arg(optIt.value().toBool() ? QStringLiteral("true") : QStringLiteral("false"));
                    } else if (key == QStringLiteral("touchpadNaturalScroll") || key == QStringLiteral("natural_scroll")) {
                        out << QString("      natural_scroll = %1,\n").arg(optIt.value().toBool() ? QStringLiteral("true") : QStringLiteral("false"));
                    } else if (key == QStringLiteral("keyboardRepeatRate") || key == QStringLiteral("repeat_rate")) {
                        out << QString("      repeat_rate = %1,\n").arg(optIt.value().toInt());
                    } else if (key == QStringLiteral("keyboardRepeatDelay") || key == QStringLiteral("repeat_delay")) {
                        out << QString("      repeat_delay = %1,\n").arg(optIt.value().toInt());
                    } else {
                        out << QString("      [\"%1\"] = \"%2\",\n").arg(key, optIt.value().toString());
                    }
                }
            }
            out << "    },\n";
        }
        out << "  },\n";
    }

    out << "}\n";
    return lua;
}

QString InputConfig::generateConfConfig() const {
    QString conf;
    QTextStream out(&conf);
    out << "# Generated by Caelestia Input Config Manager\n";
    out << "# Do not edit directly; values are persisted in shell.json\n\n";
    out << "input {\n";
    out << QString("    sensitivity = %1\n").arg(pointerSpeed());
    out << "    touchpad {\n";
    out << QString("        tap-to-click = %1\n").arg(touchpadTapToClick() ? QStringLiteral("true") : QStringLiteral("false"));
    out << QString("        natural_scroll = %1\n").arg(touchpadNaturalScroll() ? QStringLiteral("true") : QStringLiteral("false"));
    out << "    }\n";
    out << QString("    repeat_rate = %1\n").arg(keyboardRepeatRate());
    out << QString("    repeat_delay = %1\n").arg(keyboardRepeatDelay());
    out << "}\n\n";

    const QVariantMap devMap = devices();
    for (auto it = devMap.constBegin(); it != devMap.constEnd(); ++it) {
        out << "device {\n";
        out << QString("    name = %1\n").arg(it.key());
        if (it.value().canConvert<QVariantMap>()) {
            const QVariantMap devOpts = it.value().toMap();
            for (auto optIt = devOpts.constBegin(); optIt != devOpts.constEnd(); ++optIt) {
                QString key = optIt.key();
                if (key == QStringLiteral("pointerSpeed") || key == QStringLiteral("sensitivity")) {
                    out << QString("    sensitivity = %1\n").arg(optIt.value().toDouble());
                } else if (key == QStringLiteral("touchpadTapToClick") || key == QStringLiteral("tap_to_click")) {
                    out << QString("    tap-to-click = %1\n").arg(optIt.value().toBool() ? QStringLiteral("true") : QStringLiteral("false"));
                } else if (key == QStringLiteral("touchpadNaturalScroll") || key == QStringLiteral("natural_scroll")) {
                    out << QString("    natural_scroll = %1\n").arg(optIt.value().toBool() ? QStringLiteral("true") : QStringLiteral("false"));
                } else if (key == QStringLiteral("keyboardRepeatRate") || key == QStringLiteral("repeat_rate")) {
                    out << QString("    repeat_rate = %1\n").arg(optIt.value().toInt());
                } else if (key == QStringLiteral("keyboardRepeatDelay") || key == QStringLiteral("repeat_delay")) {
                    out << QString("    repeat_delay = %1\n").arg(optIt.value().toInt());
                } else {
                    out << QString("    %1 = %2\n").arg(key, optIt.value().toString());
                }
            }
        }
        out << "}\n\n";
    }

    return conf;
}

QString InputConfig::generateConfig(bool forceLua) const {
    if (usingLua() || forceLua) {
        return generateLuaConfig();
    }
    return generateConfConfig();
}

bool InputConfig::saveGeneratedConfig(const QString& customFilePath, bool forceLua) {
    QString targetPath = customFilePath;
    const bool isLua = usingLua() || forceLua;
    if (targetPath.isEmpty()) {
        QString configDir = QStandardPaths::writableLocation(QStandardPaths::GenericConfigLocation) + QStringLiteral("/caelestia/generated/");
        QDir().mkpath(configDir);
        targetPath = configDir + (isLua ? QStringLiteral("input.lua") : QStringLiteral("input.conf"));
    } else {
        QFileInfo info(targetPath);
        QDir().mkpath(info.absolutePath());
    }

    QString content = generateConfig(isLua);

    QSaveFile saveFile(targetPath);
    if (!saveFile.open(QIODevice::WriteOnly | QIODevice::Text)) {
        qCWarning(lcConfig) << "InputConfig::saveGeneratedConfig: Unable to open QSaveFile for" << targetPath;
        return false;
    }

    QTextStream out(&saveFile);
    out << content;
    out.flush();

    if (!saveFile.commit()) {
        qCWarning(lcConfig) << "InputConfig::saveGeneratedConfig: Atomic commit failed for" << targetPath;
        return false;
    }

    ensureConfigConsumed(targetPath, isLua);
    syncVariablesFile();

    return true;
}

void InputConfig::ensureConfigConsumed(const QString& generatedFilePath, bool forceLua) {
    const bool isLua = usingLua() || forceLua;
    QString genPath = generatedFilePath;
    if (genPath.isEmpty()) {
        QString configDir = QStandardPaths::writableLocation(QStandardPaths::GenericConfigLocation) + QStringLiteral("/caelestia/generated/");
        genPath = configDir + (isLua ? QStringLiteral("input.lua") : QStringLiteral("input.conf"));
    }

    if (isLua) {
        QString configBase = QStandardPaths::writableLocation(QStandardPaths::GenericConfigLocation);
        QStringList luaCandidates = {
            configBase + QStringLiteral("/hypr/hyprland.lua"),
            configBase + QStringLiteral("/caelestia/hyprland.lua")
        };

        bool foundTarget = false;
        for (const QString& luaPath : luaCandidates) {
            QFile file(luaPath);
            if (file.exists()) {
                foundTarget = true;
                if (file.open(QIODevice::ReadOnly | QIODevice::Text)) {
                    QString content = QString::fromUtf8(file.readAll());
                    file.close();
                    if (!content.contains(QStringLiteral("caelestia/generated/input.lua")) &&
                        !content.contains(QStringLiteral("input.lua"))) {
                        if (file.open(QIODevice::Append | QIODevice::Text)) {
                            QTextStream out(&file);
                            out << QStringLiteral("\n\n-- Caelestia Input Configuration\n"
                                                  "local _caelestia_input = os.getenv(\"HOME\") .. \"/.config/caelestia/generated/input.lua\"\n"
                                                  "if io.open(_caelestia_input, \"r\") then\n"
                                                  "    local _ok, _cfg = pcall(dofile, _caelestia_input)\n"
                                                  "    if _ok and type(_cfg) == \"table\" and hl and hl.config then\n"
                                                  "        hl.config(_cfg)\n"
                                                  "    end\n"
                                                  "end\n");
                            file.close();
                        }
                    }
                }
            }
        }

        if (!foundTarget) {
            QString primaryLua = configBase + QStringLiteral("/hypr/hyprland.lua");
            QFileInfo info(primaryLua);
            QDir().mkpath(info.absolutePath());
            QFile file(primaryLua);
            if (file.open(QIODevice::WriteOnly | QIODevice::Text)) {
                QTextStream out(&file);
                out << QStringLiteral("-- Authoritative Hyprland Lua Configuration\n"
                                      "local hl = require(\"hyprland\")\n\n"
                                      "-- Caelestia Input Configuration\n"
                                      "local _caelestia_input = os.getenv(\"HOME\") .. \"/.config/caelestia/generated/input.lua\"\n"
                                      "if io.open(_caelestia_input, \"r\") then\n"
                                      "    local _ok, _cfg = pcall(dofile, _caelestia_input)\n"
                                      "    if _ok and type(_cfg) == \"table\" and hl and hl.config then\n"
                                      "        hl.config(_cfg)\n"
                                      "    end\n"
                                      "end\n");
                file.close();
            }
        }
    } else {
        QString configBase = QStandardPaths::writableLocation(QStandardPaths::GenericConfigLocation);
        QString userConf = configBase + QStringLiteral("/caelestia/hypr-user.conf");
        QString sourceLine = QStringLiteral("source = ") + genPath;

        QFileInfo info(userConf);
        QDir().mkpath(info.absolutePath());

        bool alreadySourced = false;
        if (QFile::exists(userConf)) {
            QFile file(userConf);
            if (file.open(QIODevice::ReadOnly | QIODevice::Text)) {
                QString content = QString::fromUtf8(file.readAll());
                file.close();
                if (content.contains(genPath) || content.contains(QStringLiteral("generated/input.conf"))) {
                    alreadySourced = true;
                }
            }
        }

        if (!alreadySourced) {
            QFile file(userConf);
            if (file.open(QIODevice::Append | QIODevice::Text)) {
                QTextStream out(&file);
                out << QStringLiteral("\n# Caelestia Input Configuration\n") << sourceLine << QStringLiteral("\n");
                file.close();
            }
        }
    }
}

void InputConfig::syncVariablesFile() {
    QString configDir = QStandardPaths::writableLocation(QStandardPaths::GenericConfigLocation) + QStringLiteral("/caelestia/");
    QDir().mkpath(configDir);
    QString varsFilePath = configDir + QStringLiteral("hypr-vars.conf");

    QFile file(varsFilePath);
    QStringList lines;
    if (file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        QTextStream in(&file);
        while (!in.atEnd()) {
            lines.append(in.readLine());
        }
        file.close();
    }

    struct VarDef {
        QString name;
        QString value;
        bool found = false;
    };

    QList<VarDef> vars = {
        { QStringLiteral("$pointerSensitivity"), QString::number(pointerSpeed()) },
        { QStringLiteral("$touchpadTapToClick"), touchpadTapToClick() ? QStringLiteral("true") : QStringLiteral("false") },
        { QStringLiteral("$touchpadNaturalScroll"), touchpadNaturalScroll() ? QStringLiteral("true") : QStringLiteral("false") },
        { QStringLiteral("$kbRepeatRate"), QString::number(keyboardRepeatRate()) },
        { QStringLiteral("$kbRepeatDelay"), QString::number(keyboardRepeatDelay()) }
    };

    for (int i = 0; i < lines.size(); ++i) {
        QString trimmed = lines[i].trimmed();
        for (auto& var : vars) {
            if (trimmed.startsWith(var.name + QStringLiteral(" ")) ||
                trimmed.startsWith(var.name + QStringLiteral("="))) {
                lines[i] = var.name + QStringLiteral(" = ") + var.value;
                var.found = true;
                break;
            }
        }
    }

    for (const auto& var : vars) {
        if (!var.found) {
            lines.append(var.name + QStringLiteral(" = ") + var.value);
        }
    }

    QSaveFile saveFile(varsFilePath);
    if (saveFile.open(QIODevice::WriteOnly | QIODevice::Text)) {
        QTextStream out(&saveFile);
        for (const auto& line : lines) {
            out << line << "\n";
        }
        out.flush();
        saveFile.commit();
    }
}

bool InputConfig::dispatchCompositorIpc() {
    const auto his = qEnvironmentVariable("HYPRLAND_INSTANCE_SIGNATURE");
    if (his.isEmpty()) {
        return false;
    }

    auto hyprDir = QString("%1/hypr/%2").arg(qEnvironmentVariable("XDG_RUNTIME_DIR"), his);
    if (!QDir(hyprDir).exists()) {
        hyprDir = QStringLiteral("/tmp/hypr/") + his;
        if (!QDir(hyprDir).exists()) {
            return false;
        }
    }

    QString socketPath = hyprDir + QStringLiteral("/.socket.sock");
    QLocalSocket socket;
    socket.connectToServer(socketPath);
    if (!socket.waitForConnected(150)) {
        qCWarning(lcConfig) << "InputConfig::dispatchCompositorIpc: Socket connection failed for" << socketPath;
        return false;
    }

    QStringList cmds;

    cmds.append(QStringLiteral("keyword input:sensitivity %1").arg(pointerSpeed()));
    cmds.append(QStringLiteral("keyword input:touchpad:tap-to-click %1").arg(touchpadTapToClick() ? 1 : 0));
    cmds.append(QStringLiteral("keyword input:touchpad:natural_scroll %1").arg(touchpadNaturalScroll() ? 1 : 0));
    cmds.append(QStringLiteral("keyword input:repeat_rate %1").arg(keyboardRepeatRate()));
    cmds.append(QStringLiteral("keyword input:repeat_delay %1").arg(keyboardRepeatDelay()));

    const QVariantMap devMap = devices();
    for (auto it = devMap.constBegin(); it != devMap.constEnd(); ++it) {
        if (it.value().canConvert<QVariantMap>()) {
            const QVariantMap opts = it.value().toMap();
            for (auto oIt = opts.constBegin(); oIt != opts.constEnd(); ++oIt) {
                QString k = oIt.key();
                if (k == QStringLiteral("pointerSpeed") || k == QStringLiteral("sensitivity")) {
                    cmds.append(QStringLiteral("keyword device[%1]:sensitivity %2").arg(it.key()).arg(oIt.value().toDouble()));
                } else if (k == QStringLiteral("touchpadTapToClick") || k == QStringLiteral("tap_to_click")) {
                    cmds.append(QStringLiteral("keyword device[%1]:tap-to-click %2").arg(it.key()).arg(oIt.value().toBool() ? 1 : 0));
                } else if (k == QStringLiteral("touchpadNaturalScroll") || k == QStringLiteral("natural_scroll")) {
                    cmds.append(QStringLiteral("keyword device[%1]:natural_scroll %2").arg(it.key()).arg(oIt.value().toBool() ? 1 : 0));
                } else if (k == QStringLiteral("keyboardRepeatRate") || k == QStringLiteral("repeat_rate")) {
                    cmds.append(QStringLiteral("keyword device[%1]:repeat_rate %2").arg(it.key()).arg(oIt.value().toInt()));
                } else if (k == QStringLiteral("keyboardRepeatDelay") || k == QStringLiteral("repeat_delay")) {
                    cmds.append(QStringLiteral("keyword device[%1]:repeat_delay %2").arg(it.key()).arg(oIt.value().toInt()));
                }
            }
        }
    }

    QString payload = QStringLiteral("[[BATCH]]") + cmds.join(QStringLiteral(";"));
    socket.write(payload.toUtf8());
    socket.flush();

    if (!socket.waitForBytesWritten(150)) {
        qCWarning(lcConfig) << "InputConfig::dispatchCompositorIpc: Socket write failed";
        socket.close();
        return false;
    }

    if (socket.waitForReadyRead(150)) {
        QByteArray response = socket.readAll();
        qCDebug(lcConfig) << "InputConfig::dispatchCompositorIpc: Response received:" << response;
    }

    socket.close();
    return true;
}

} // namespace caelestia::config
